def throw_error(err):
    raise Exception(err)